### ISSUE TITLE
少类

### ISSUE THREAD

**Issue by qidianli** [zhpanvip/Retrofit2#13]
com.zhpan.idea.net.common.DefaultObserver

**Comment by zhpanvip** [comment]
改名字了，ResponseObserver.

**Comment by qidianli** [comment]
好的，谢谢，请问这个在实际项目中效果如何?可靠吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhpanvip"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午4:54
收件人:&nbsp;"zhpanvip/Retrofit2"<Retrofit2@noreply.github.com&gt;;
抄送:&nbsp;"ZYCJ"<1427572350@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhpanvip/Retrofit2] 少类 (#13)





 
改名字了，ResponseObserver.

**Comment by zhpanvip** [comment]
已经在项目里边跑了两年了。

**Comment by qidianli** [comment]
谢谢大神



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhpanvip"<notifications@github.com&gt;; 
发送时间: 2020年4月20日(星期一) 下午5:03
收件人: "zhpanvip/Retrofit2"<Retrofit2@noreply.github.com&gt;; 
抄送: "ZYCJ"<1427572350@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhpanvip/Retrofit2] 少类 (#13)





 
已经在项目里边跑了两年了。
