### ISSUE TITLE
NetworkInterceptor 

### ISSUE THREAD

**Issue by houyuehai** [zhpanvip/Retrofit2#2]
网络断路 不是不会跑 NetworkInterceptor 
那么你在NetworkInterceptor 里面强制使用缓存 这个我不理解 
 我打了断点 当网络断路（4Gwifi都没有）是不会跑NetworkInterceptor 的。
很奇怪 能帮我解答下嘛？

**Comment by zhpanvip** [comment]
api上加@Headers("Cache-Control: public, max-age=100")。100是缓存时间100s

**Comment by houyuehai** [comment]
明白了，当有网络并且服务器有响应时，在拦截里标记响应数据将缓存100s，下次去访问同样的数据（100s内，断网情况下），okhttp会自动采用缓存的数据，并且只有GET方式下有效，若要实现POST需要在拦截里实现。感谢您的回复。
