### ISSUE TITLE
一点小疑问???

### ISSUE THREAD

**Issue by lydlovezjr** [zhpanvip/Retrofit2#5]
可否不在GsonResponseBodyConverter处理数据,直接还是返回整个实体,因为有时候需要根据Code判断!!!

**Comment by zhpanvip** [comment]
返回的错误码已经被捕捉到ServerResponseException里边了，所以对于需要判断code的可以在ServerResponseException里边处理。如果你不觉得麻烦想返回整个实体类自行把GsonResponseBodyConverter去掉就行了。

**Comment by lydlovezjr** [comment]
谢大佬
